# Generated by Django 6.0.2 on 2026-02-22 10:33

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='MasterClass',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='Название мастер-класса')),
                ('description', models.CharField(max_length=200, verbose_name='Краткое описание')),
                ('count', models.IntegerField(verbose_name='Количество доступных мест для записи')),
                ('date_event', models.DateField(verbose_name='Дата проведения')),
                ('duration', models.CharField(max_length=200, verbose_name='Продолжительность занятие')),
                ('format', models.IntegerField(choices=[(1, 'Очная встреча'), (2, 'Онлайн')], verbose_name='Формат')),
                ('price', models.DecimalField(decimal_places=2, max_digits=7, verbose_name='Стоимость участия')),
                ('method_payment', models.IntegerField(choices=[(1, 'Банковская плата'), (2, 'Онлайн-перевод')], verbose_name='Способы оплаты')),
                ('status', models.IntegerField(choices=[(1, 'Черновик'), (2, 'Опубликован'), (3, 'Идёт проведение'), (4, 'Завершён'), (5, 'Откланён')], default=1)),
                ('comment', models.CharField(max_length=200)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.category', verbose_name='Категория')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='ProfileUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fio', models.CharField(max_length=200)),
                ('phone', models.CharField(max_length=15)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
