# Generated by Django 6.0.2 on 2026-02-22 10:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='masterclass',
            name='comment',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
