# Generated by Django 6.0.2 on 2026-02-25 15:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_alter_masterclass_comment'),
    ]

    operations = [
        migrations.CreateModel(
            name='Tema',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
            ],
        ),
        migrations.AlterField(
            model_name='masterclass',
            name='category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.category', verbose_name='Направление'),
        ),
        migrations.AlterField(
            model_name='masterclass',
            name='status',
            field=models.IntegerField(choices=[(1, 'Черновик'), (2, 'Опубликован'), (3, 'Идёт проведение'), (4, 'Завершён'), (5, 'Отклонён')], default=1),
        ),
        migrations.AddField(
            model_name='masterclass',
            name='tema',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='main.tema', verbose_name='Категория'),
            preserve_default=False,
        ),
    ]
