# Generated by Django 6.0.2 on 2026-02-25 15:58

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_tema_alter_masterclass_category_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='masterclass',
            name='category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.category', verbose_name='Категория'),
        ),
        migrations.AlterField(
            model_name='masterclass',
            name='tema',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.tema', verbose_name='Тема'),
        ),
    ]
