# Generated by Django 6.0.2 on 2026-02-25 16:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_alter_masterclass_category_alter_masterclass_tema'),
    ]

    operations = [
        migrations.AddField(
            model_name='tema',
            name='category',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='temas', to='main.category'),
            preserve_default=False,
        ),
    ]
