# Generated by Django 6.0.2 on 2026-03-06 09:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_tema_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='masterclass',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='masterclass_images/', verbose_name='Изображение курса'),
        ),
        migrations.AlterField(
            model_name='masterclass',
            name='duration',
            field=models.CharField(max_length=200, verbose_name='Адрес занятие'),
        ),
        migrations.AlterField(
            model_name='masterclass',
            name='method_payment',
            field=models.IntegerField(choices=[(1, 'Банковская карта'), (2, 'Онлайн-перевод'), (3, 'Наличные')], verbose_name='Способы оплаты'),
        ),
        migrations.AlterField(
            model_name='masterclass',
            name='status',
            field=models.IntegerField(choices=[(1, 'Черновик'), (2, 'На модерации'), (3, 'Опубликован'), (4, 'Идёт проведение'), (5, 'Завершён'), (6, 'Отклонён')], default=1),
        ),
        migrations.AlterField(
            model_name='profileuser',
            name='phone',
            field=models.CharField(max_length=11),
        ),
    ]
